# Generated by Django 4.0.3 on 2022-03-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_handtime', '0004_addproduct_wishlists_carts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='producttype',
        ),
    ]
